### ISSUE TITLE
Middle click ("open link in a new tab") misbehaves and moves to the targeted page

### ISSUE THREAD

**Issue by chikamichi** [lairdubois/lairdubois#1]
Hi,

When a user middle-clicks (or ctrl-clicks) on a *lairdubois.com*'s link, it does open in a new tab as expected, but the current tab incorrectly moves the user to the targeted page as well. It should not.

Likely to be a JavaScript issue (I haven't check the source code yet).

**Comment by bbeaulant** [comment]
Hi,

This only appear when you click on a creation thumbnail in creations list, no ?
Like this screenshot :
![capture d ecran 2016-11-20 a 20 29 56](https://cloud.githubusercontent.com/assets/156056/20465569/3bfc5b92-af60-11e6-9ccf-50459141db20.png)

I think the problem is located here 

src/ladb/CoreBundle/Resources/views/Common/_masonry-list-thumbnail.part.html.twig
`    <div class="ladb-box"{% block onClickOuter %} onclick="if (event.target.tagName != 'A' && $(event.target).parent().prop('tagName') != 'A') { {% block onClickInner %}document.location = '{{ ladb_entity_url_action(entity) }}';{% endblock %} }"{% endblock %}>
`

**Comment by chikamichi** [comment]
Yes, my message was a bit misleading: it only affects thumbnails.

I guess this code is a Masonry given, and you are pulling Masonry automatically through a package manager? I browsed through the options for the lib and didn't find an API to opt-out of this behavior, which is unfortunate.

**Comment by chikamichi** [comment]
Oh, actually (I'm not a PHP guy ;), looking at the url, isn't that a Symphony view you have full control over? In that case, the fix would be quite easy to implement :)

**Comment by bbeaulant** [comment]
Yes we have full control on this view part. I think that the `onclick` JS only need to check the `event.button` property. But as the click on not on a A tag, but just on a DIV or what else it contains, how to do what we want ? 
It's easy to avoid the double opening tab :

`onclick="if (event.target.tagName != 'A' && $(event.target).parent().prop('tagName') != 'A' && **event.button == 0**) {...}`

But it's not realy what we want ;)

**Comment by chikamichi** [comment]
There are a couple issues to work around:

1. there is no truly cross-browser, reliable JS API to "open in a new tab"; `window.open` is the closest, but has real shortcomings and cross-compatibility issues;
2. the click event is handled by a `div`, so direct event propagation/bubbling won't trigger native `A` tag's behaviors; especially `target='_blank'`, which would come in handy.

The second issue is not really a problem, as long as the processed click event is *forwarded* to a true anchor tag with the appropriate attributes. This tag doesn't even have to pre-exist statically in the page. The other core idea to support arbitrary click behaviors (same tab or new tab) is to monitor which "key" the click was triggered by, as you said. Finally, the trick lies in promoting "open in a new tab" as the *default* behaviour to work around the first issue.

Implementing all this using inline JS is tough though, so let me define a function instead:

``` js
// Using jQuery to get things done faster, as I noticed it is used on lairdubois.fr
var openMasonryLink = function(e) {
  var link_location = $(e.target).data('link-location');
  console.log('openMasonryLink', link_location);
  
  // Emulate an "open in a new tab" kind of click by default.
  if (e.ctrlKey || e.shiftKey || e.metaKey || (e.button && e.button == 1)) {
    var $anchor = $('<a>').hide().attr({
      href: link_location,

      target: '_blank',
      class: 'ladb-masonry-transient-link'
    });
    $anchor.appendTo('body');
    var $link = $('.ladb-masonry-transient-link');
    $link[0].click();
    $link.remove();
    return; // And/Or return false, e.preventDefault, etc.
  
  // Regular click actually? Let's just move to the specified location.  
  } else {
    document.location = link_location;
    return;
  }
};
```

Now the only required edit in the view is as follow:

``` twig
<div class="ladb-box"{% block onClick %} onclick="openMasonryLink(event);" data-link-location="{{ ladb_entity_url_action(entity) }}"{% endblock %}>
```

**Comment by chikamichi** [comment]
Note: if you read my previous message through your mail client, please go to github.com as I've made some edits which won't be reflected in the mail notification. :see_no_evil:

**Comment by chikamichi** [comment]
@bbeaulant have you got any chance to try it? :)

**Comment by bbeaulant** [comment]
Yes, sorry, I'm a little buzzy this week to try it. But as I can see your code open link in a new _blank and then focus it. Is it what we want ? This is not exactly the default behavior.

**Comment by chikamichi** [comment]
> your code open link in a new _blank and then focus it. Is it what we want ? This is not exactly the default behavior.

No, it's not. On regular clicks it will assign `document.location`. But if a middle-click / ctrl-click is detected, it will emulate a click on a link with `target=_blank`, which works just fine cross-browser.

**Comment by bbeaulant** [comment]
Yes, of course the main button click go to the correct location. What I say is that the default "middle-click" behavior is to open the link in a new tab in background, not foreground.

**Comment by chikamichi** [comment]
:+1: 

Of course having the link focus its tab is not as nice as the native behaviour where it opens in the background, but at least it prevents from messing with the current tab. Thank you very much for incorporating my idea and deploying in production!

**Comment by bbeaulant** [comment]
Thank you for your contribution ;)
