### ISSUE TITLE
Livre en plusieurs volumes: limitation de la longueur du titre du volume ?

### ISSUE THREAD

**Issue by drazib** [lairdubois/lairdubois#103]
Bonjour les développeurs,
Alors j'ai bataillé pendant deux jours pour essayer d'ajouter un livre qui était en deux volumes.
Impossible de valider la création de la chose, erreur 500 du serveur.

Je viens de réessayer aujourd'hui, il semblerait que la chaîne de caractères pour le titre du volume était trop longue.
J'ai réussi à mettre finalement `2me cahier de géométrie, dessin technique et constr` alors que j'aurais bien aimé mettre `2me cahier de géométrie, dessin technique et construction. Objets usuels de menuiserie`.

D'où mes question et remarque:
1. est ce qu'il y a bien une limite de nombre de caractères ? (51 ???)
2. si oui, ce serait pas mal de l'indiquer à l'utilisateur, parce que j'ai cru que j'avais rentré trop de livre d'un coup (14!) et que ça voulait plus...

PS:  pour info, la page en question:
https://www.lairdubois.fr/livres/511-les-cahiers-de-lapprenti-menuisier-en-batiment-1.html

**Comment by bbeaulant** [comment]
Hmm, l'erreur 500 est étrange. La taille devrait être contrôlée avant.

La taille du titre de volume est limité à 100 caractères.
https://github.com/lairdubois/lairdubois/blob/4fe98c49a4611ae7bca9fbe8959084ab3cc891e7/src/Ladb/CoreBundle/Entity/Knowledge/Value/BookIdentity.php#L41

Mais c'est pas faux qu'il y a un truc qui tronque quelque part. Il faudra que je creuse ça.

**Comment by bbeaulant** [comment]
Voilà qui est corrigé. Il y a un champ qui porte le concaténation du titre principal + titre du volume et il était lui aussi limité à 100 caractères.
