### ISSUE TITLE
Servir une version allégée (ou pas) de OCL dans l'Air Du Bois

### ISSUE THREAD

**Issue by pimpin** [lairdubois/lairdubois#106]
Bonjour bonjour,
Je me dis qu'il pourrait être intéressant de porter les fonctionnalité de OCL dans l'AirDuBois...
Pourquoi se casserait-on la tête à saisir sa nomenclature dans le site quand c'est tout automatisé dans Sketchup ? Car je ne me suis toujours pas motivé pour payer une licence Sketchup assez chère vu mon usage d'amateur du dimanche, et que la seule version gratuite de Sketchup est une version full web qui ne permet pas de charger des extensions.
Et soyons fous... le service pourrait peut être prendre des fichiers skp en entrée pour ne pas avoir à saisir la liste de ses pièces...
Pensez-vous que le besoin soit suffisament partagé pour envisager cette fonction ? Je suis prêt à contribuer, car si je suis boiseux novice amateur, je suis aussi Rubyist plus confirmé ...

**Comment by bbeaulant** [comment]
Bonjour Pierre,

Merci pour cette proposition de contribution. Mais en l'état, OpenCutList a totalement besoin de l'architecture de SketchUp pour fonctionner.
Ce que je veux dire par là, c'est que la fonction que tu décris nécessite une réécriture complète d'un outil capable de lire des fichiers 3D et d'en extraire une fiche de débit. En ruby ou autre, du moment que c'est autonome et que ça tourne sous Linux s'il doit être lancé sur le serveur de L'Air du Bois.

Je peine à en voir la plus value d'un tel outil s'il n'est pas intégré au logiciel 3D directement 🤔

**Comment by seb-troiani** [comment]
Salut Pierre 🖖
Je suis aussi Sketcheur du dimanche et j'utilise Sketchup Make, qui était la version gratuite avant Sketchup 2018 et avant que la version gratuite devienne une version web only.
Make fonctionne parfaitement, y compris avec les différents greffons de l'ADB ou BLB.
WoS: Recherche le fichier sketchupmake-2017-2-2555-90783-fr-x64.exe sur le net - ça se trouve facile mais évidemment plus chez Trimble 😉
Hope this helps !

**Comment by pimpin** [comment]
Merci Boris et Seb pour vos réponses.
J'ai trouvé la version MacOs je vais l'essayer un peu pour voir si ça tourne correctement.
Je n'ai pas lu le code d'OCL pour comprendre ce que représenterait le portage de l'extention en service autonome.
Mais on y gagnerait de l'autonomie... et ce n'est pas une plus value négligeable.
Fermons cette issue... il sera temps de la réouvrir si cela fait de nouveau sens; par exemple le jour où Sketchup 2017 ne tournera plus dans nos OS, peut etre qu'il y aura alors beaucoup d'utilisateurs d'OCL qui motiveront ce projet.
Bonne soirée
