### ISSUE TITLE
Une nouvelle

### ISSUE THREAD

**Issue by hedjour** [lairdubois/lairdubois#11]
Désolé encore moi :s
Petite question par moment au niveau du marqueur des questions sur le coté un chiffre apparait mais impossible de voir quelle est la nouvelle question ou le nouveau commentaire / réponse qui entraine cet affichage.
Serait il possible de trier les questions par status de lecture ?
Encore une fois merci pour tout.

**Comment by bbeaulant** [comment]
Salut, pour les questions, c'est un peu comme pour les pas à pas. Ces deux types de publication on des sous contenus. **Réponse** pour les questions et **Article** pour les pas à pas.
Dans ces deux cas, il peut donc y avoir une nouveauté sans que la publication principale ne change.
Une nouvelle réponse ou un nouvel article fait donc remonter la question ou le pas à pas à tête de liste et donc s'ajoute au compteur en pastille orange dans le bandeau de gauche.

Le truc sur les question, c'est que la nouvelle réponse n'est pas forcément la réponse du haut ou du bas. Le tri par défaut c'est les score.

Il faut donc utiliser le bouton de tri des réponses en utilisant le tri "Plus récentes" pour voir apparaître en premier les nouvelles réponses. Je suis conscient, c'est pas super intuitif, mais j'avais pas trouvé mieux sur le coup.
