### ISSUE TITLE
Impossible d'aimer une creation

### ISSUE THREAD

**Issue by lyrixx** [lairdubois/lairdubois#112]
Sur cette URL https://www.lairdubois.fr/creations/17535-banc-13.html
quand je clique sur 
![image](https://github.com/lairdubois/lairdubois/assets/408368/ab900b93-e389-4709-ab70-696742665366)
Il ne se passe rien.

En effet, la réponse est une 404.

<details><summary>Requète</summary>
<p>

```
curl 'https://www.lairdubois.fr/likes/100/17535/create?rtu=/creations/17535-banc-13.html&noTextOnMobile=0&_=1708849868576' \
  -H 'authority: www.lairdubois.fr' \
  -H 'accept: text/html, */*; q=0.01' \
  -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'cookie: PHPSESSID=..........REDACTED...........' \
  -H 'dnt: 1' \
  -H 'pragma: no-cache' \
  -H 'referer: https://www.lairdubois.fr/creations/17535-banc-13.html' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'x-requested-with: XMLHttpRequest' \
  --compressed
```

</p>
</details>

**Comment by MichelDwo** [comment]
![image](https://github.com/lairdubois/lairdubois/assets/27759936/17e58ff0-5a37-4797-b620-05368fde473c)
Sur mobile, j’ai réussi à aimer.

**Comment by bbeaulant** [comment]
Seules les requêtes en AJAX sont autorisés.

**Comment by lyrixx** [comment]
@bbeaulant pourtant la requête était bien en ajax. Cf le header x-requested-with

**Comment by bbeaulant** [comment]
Dans quel but faire cette requête avec curl ?

**Comment by lyrixx** [comment]
Aucun 😁

J'ai juste fait "copy as curl" depuis chrome dev tools, pour aider au debug.
Le problème arrive avec chrome, quand je click avec ma souris.

![image](https://github.com/lairdubois/lairdubois/assets/408368/44a6cc3c-3d96-4c21-9a3f-c634b2f5e0b5)


Note : je suis développeur Symfony, alors j'essaie au debug au maximum. D'ailleurs, si t'as des soucis avec Symfony, ca serait un plaisir d'aider ce magnifique projet 💛

**Comment by bbeaulant** [comment]
Ok, pke le token ne sera jamais valide.

Sinon, je n'ai pas de soucis à ajouter ou retirer un coups de coeurs sur cette création avec mobile ou ordi sur chrome.

**Comment by lyrixx** [comment]
okay, j'ai trouvé. j'avais une 404, car mon compte n'étais pas encore actif

https://github.com/lairdubois/lairdubois/blob/master/src/Ladb/CoreBundle/Controller/Core/LikeController.php#L52-L55

maintenant qu'il l'est je n'ai plus de problème.

**Comment by bbeaulant** [comment]
Ha oui, j'avais mis ça pour limiter tous ces robots qui faisaient des likes.
