### ISSUE TITLE
faute de frappe dans les processus

### ISSUE THREAD

**Issue by fdoumange** [lairdubois/lairdubois#12]
https://github.com/lairdubois/lairdubois/blob/cfb1bde0567580767f25f7091a1b38c3b5ac7877/src/Ladb/CoreBundle/Resources/assets/js/ladb/jquery.ladb.workflowworkspace.js#L1479

Bonjour,

J'indique juste une petite faute de frappe constatée lors de la sortie du mode travail d'un processus. Il est écrit : "Vous avez été déconecté :(". Sauf erreur de ma part, il manque un "n", non ?

C'est juste un détail et peut-être est-ce déjà corrigé ?

**Comment by bbeaulant** [comment]
Merci du signalement ! C'est corrigé !
