### ISSUE TITLE
Liste des projets que l'on a aimé / trouve inspirant

### ISSUE THREAD

**Issue by sciunto** [lairdubois/lairdubois#13]
Bonjour,

Je touverais intéressant d'avoir, comme sur pinterest par exemple, un endroit où garder trace des projets que l'on a aimé pour ses réalisations futures. A moins que je ne me trompe, ça n'existe pas sur l'air du bois.

Merci !

**Comment by bbeaulant** [comment]
Il y a déjà une page pour visualiser tous les coups de coeur qu'un utilisateur a donné (ex : https://www.lairdubois.fr/zeloko/coups-de-coeur)

Ce lien est accessible sur la page A propos d'un boiseu en cliquant sur le nombre de coups de coeur envoyés.

![capture d ecran 2018-02-25 a 14 39 01](https://user-images.githubusercontent.com/156056/36642010-a8dfde74-1a39-11e8-8f29-89693203e48d.png)

**Comment by bbeaulant** [comment]
Mais il est vrai que j'avais réfléchi à une possibilité d'avoir des sorte de "Collections" dans lesquelles ont pourrait regrouper tout type de contenu (création, plan, pas à pas, etc ...).

Ces collections pourraient être publiques ou privées. 

Reste que mixer les différents contenus marche bien sur le papier mais présente des difficultés techniques à prendre le temps de réfléchir.

**Comment by bbeaulant** [comment]
Sinon, il y a toujours les favoris de ton navigateur pleinement destinés à ça ;)

**Comment by hedjour** [comment]
Une autre idée serait simplement d'ajouter un filtre pour les créations du moins mes favoris (aimé)

**Comment by bbeaulant** [comment]
Sinon, voilà qui est fait avec la création des [Collections](https://www.lairdubois.fr/blog/121-une-nouvelle-rubrique-collections.html) !

**Comment by sciunto** [comment]
Chouette ! Merci @bbeaulant
