### ISSUE TITLE
[Install] NPM is missing a package.json

### ISSUE THREAD

**Issue by marcaurele** [lairdubois/lairdubois#19]
In the [installation documentation - section 4.2](https://github.com/lairdubois/lairdubois/blob/master/docs/01-installation.md#step-42---run-npm-to-retrieve-js-dependencies), nodeJS is used to install javascript dependencies but there isn't any file `package.json`or alike (for yarn - better!). Is this file missing in the repository, or can this step be removed?

**Comment by bbeaulant** [comment]
You're right. This command is already done in step 0

```

$ npm install -g less
```
