### ISSUE TITLE
Utiliser des parenthèses dans les titres

### ISSUE THREAD

**Issue by maethor** [lairdubois/lairdubois#30]
J'ai voulu créer une question titrée ainsi : « Quel(s) bois pour les Kumiko ? ». Ça me parait assez légitime, mais le formulaire a refusé ce titre en me disant qu'il y avait des caractères interdits (mais sans m'indiquer lesquels). J'ai enlevé les parenthèses et c'est passé.

Je pense que le formulaire devrait accepter les parenthèses si possible. Mais surtout il pourrait indiquer quels caractères sont interdits.

**Comment by bbeaulant** [comment]
C'est une bonne remarque.
En cause, c'est cette expression régulière : https://github.com/lairdubois/lairdubois/blob/ae5748acce7d2fbcf171621a2bd3fe6516fb4ff4/src/Ladb/CoreBundle/Entity/Qa/Question.php#L59

Difficile du coup de donner les caractères qui ne vont pas puisque c'est tout ce qui n'est pas dans l'expression.
Bon, après se pose la question de savoir s'il est pertinent de mettre des restrictions sur les titres...

Il est par contre intéressant de noter que les parenthèses pourraient y avoir leur place.

**Comment by maethor** [comment]
À toi de voir :)

À mon avis il n'y a pas d'intérêt à mettre de restriction. Ou il faudrait la faire sous forme de blacklist, mais je ne vois pas de cas qui le justifie.

**Comment by bbeaulant** [comment]
Tu as certainement raison. D'autant qu'on aime pas les restrictions. A l'origine, c'était pour éviter les titre sans mots ou un peu trop putaclic. Mais il est clair qu'une restriction casse la créativité.
L'idée aussi était de trouver tout ce qui est possible pour s'affranchir de la modération à la main par un bon volontaire pour des choses qui pouvaient être traité à la source.

**Comment by maethor** [comment]
Tu pourrais essayer de détecter qu'il y a plus de majuscules que de minuscules, peut-être, ou que le titre est tout en majuscules. Mais bon, essayons de faire confiance aux utilisateurs et si ça crée vraiment des soucis il sera toujours temps de trouver la règle adaptée.

**Comment by bbeaulant** [comment]
Hihi, ce test y est déjà. Limite à 1/3 de majuscules.
Mais ça va pas trop. Genre une collection en "TODO List", ça passe pas.
Peut-être faudrait que la longueur soit d'au moins 20 caractères

**Comment by bbeaulant** [comment]
Contraintes retirées sur les titres :)
