### ISSUE TITLE
Bloc navigation dans un formulaire avec une faible largeur d'écran

### ISSUE THREAD

**Issue by maethor** [lairdubois/lairdubois#32]
J'ai l'habitude de travailler en écran splitté, ce qui fait que mon navigateur n'a qu'une largeur de 916 pixels. Dans cette largeur d'écran il y a 2 choses qui pourraient être améliorées dans les vues formulaires (par exemple créer un article, ou une question).

1. Le bloc de navigation n'a pas besoin d'être affiché, et le bouton « Enregistrer » devrait être en bas du formulaire. Là je rempli ma page et je dois remonter en haut pour enregistrer.

![2019-03-14-120330_956x1036_scrot](https://user-images.githubusercontent.com/2410576/54352332-ba18e600-4651-11e9-8d97-da777baa9786.png)

2. Le bloc en question reste fixe et se retrouve sous le formulaire quand on commence à scroller, c'est assez moche.

![2019-03-14-120340_956x1036_scrot](https://user-images.githubusercontent.com/2410576/54352341-bedd9a00-4651-11e9-9e29-547860c9b44b.png)

**Comment by bbeaulant** [comment]
Hmm, c'est pas faux. Le second bug est facile à corriger.
La première remarque demande de s'y pencher ;)
