### ISSUE TITLE
how to install on windows

### ISSUE THREAD

**Issue by amitsavla** [lairdubois/lairdubois#4]
hi,

suggest me for windows installation

**Comment by bbeaulant** [comment]
That a good question. I don't have the full anwser.
L'Air du Bois is based on Symfony PHP framework, then first you can inspire on how the Symfony doc explain the setup process on Windows.

http://symfony.com/doc/current/setup.html

**Comment by amitsavla** [comment]
Thank you sir, then have need to work on this for windows installation. 
Can you provide .sql files?

amit_savla@outlook.com

**Comment by bbeaulant** [comment]
You don't need SQL files. The database structure can be generated by command line.
Just follow the [setup instructions](https://github.com/lairdubois/lairdubois/blob/master/docs/01-installation.md#step-7---setup-the-database).

**Comment by bbeaulant** [comment]
But I think that installing all necessary tools on Windows could be a really big nightmare ...
My be it would be preferable to find a Linux distrib :P

**Comment by marcaurele** [comment]
@amitsavla if you have a procedure to install the software on Windows, we'll be happy to get your contribution to add this how-to in the docs. Feel free to push a PR with it.
I guess, @bbeaulant, the issue can be closed as it's not a system target for the app.
