### ISSUE TITLE
Un bouton tout marquer comme lu

### ISSUE THREAD

**Issue by hedjour** [lairdubois/lairdubois#41]
Avoir un petit bouton dans un coin pour tout marquer comme lu pour retirer les petites marques oranges en bas à droite de tous les éléments.
Utile pour quand on revient de vacances et qu'il y a 250 nouveautés...
Merci

**Comment by bbeaulant** [comment]
Tu veux dire dans les notifications ?

**Comment by hedjour** [comment]
Aussi, je pensais surtout au petit point orange qui s'affiche dans chaque rubrique.

**Comment by bbeaulant** [comment]
Tu veux parler de celui-la ?
![Capture d’écran 2019-08-26 à 15 40 11](https://user-images.githubusercontent.com/156056/63695009-fca53800-c817-11e9-859e-db4624864212.png)

**Comment by hedjour** [comment]
oui :)

**Comment by bbeaulant** [comment]
Ha, ben je vois pas bien l'intérêt de les marquer comme vu si tu les as pas vu, alors.
C'est pas bien grave si la pastille s'affiche, non ?
Et puis tu peux y revenir dans 1 an et savoir que tu ne l'as jamais ouvert.

Sans compter que pour enregistrer que tu l'as vu, c'est une ligne en plus dans le base de données. Donc de l'information stockée pour qqch qui ne s'est même pas passé :)

**Comment by hedjour** [comment]
ok c'est pas faux :) si en plus ça permet d'éviter de stocker des données pour rien.
