### ISSUE TITLE
Page Fournisseur

### ISSUE THREAD

**Issue by hedjour** [lairdubois/lairdubois#5]
Plus une précision qu'une erreur.
Il peut être bon de préciser sur quoi se fait la recherche par localisation code département code postale.
Ce qui serait top c'est si on entre deux chiffres la recherche se fait sur les deux premiers caractère du code postal si on en entre 4 la recherche se fait sur le code postal.

**Comment by bbeaulant** [comment]
Hmm, à cette heure, c'est pas si poussé que ça. Ca se passe par ici : 
https://github.com/lairdubois/lairdubois/blob/master/src/Ladb/CoreBundle/Controller/ProviderController.php#L202

En fait la recherche avec la localisation se fait juste sur l'adresse et la zone géographique (constituée du pays, région, département, ville).

**Comment by hedjour** [comment]
Je regarde ça dès que je peux, pour faire des propositions

**Comment by bbeaulant** [comment]
Depuis j'ai changé un peu le principe de recherche par localisation. Ca transforme la valeur de recherche en zone géographique et ça sort tous les résultat qui s'y trouvent.
