### ISSUE TITLE
Compteurs de nouveaux éléments non systématiquement remis à zéro

### ISSUE THREAD

**Issue by floriancargoet** [lairdubois/lairdubois#52]
Depuis ce matin, les compteurs oranges dans le menu de gauche ne se remette plus systématiquement à zéro quand je visite les différentes sections.
Je peux aller de section en section sans aucune remise à zéro mais parfois sans que j'identifie la raison, un compteur sera remis à zéro.

**Comment by bbeaulant** [comment]
Arf, oui. Il y a un consumer en background (via une pile mise dans RabbitMQ) qui traite les vues et il était rentré dans un état instable et peinanait à traiter tout ça. Je l'ai relance et ça devrait plus le faire pour le moment.
