### ISSUE TITLE
Disparition de la barre de tri/filtre quand on choisit "Coups de projecteur"

### ISSUE THREAD

**Issue by floriancargoet** [lairdubois/lairdubois#53]
Sur l'onglet "Créations" de la page profil, si on choisit "Coups de projecteur" dans le menu "Populaires" alors qu'il n'y a pas de création ayant reçu un coup de projecteur, le menu de tri/filtrage disparait entièrement. 

![image](https://user-images.githubusercontent.com/110431/74585829-8b358d80-4fe1-11ea-9bc8-69d6c34f904e.png)

On s'attend à ce que le menu reste pour pouvoir changer de filtre.
Le message quand à lui pourrait être plus précis et dire qu'il n'y a pas de créations correspondant au filtre plutôt que de dire qu'aucune n'a été publiée.

**Comment by bbeaulant** [comment]
Arg, oui, c'est pas faux.
Et en même temps, ces pages sont dans une "todo list" pour contenir la même barre de filtre, tri et recherche que les pages principales des rubriques. Ca serait plus homogène et éviterait les doublons de code :)

> Le message quand à lui pourrait être plus précis et dire qu'il n'y a pas de créations correspondant au filtre plutôt que de dire qu'aucune n'a été publiée.

C'est vrai. Le message correspond pour le moment à ce qui était attendu quand l'utilisateur n'avait encore rien publié de ce type.

Une petite ou une grosse rustine sont donc possible pour corriger ça :)

**Comment by bbeaulant** [comment]
Résolu en retirant la notion de "filtre" à cet endroit.

https://github.com/lairdubois/lairdubois/commit/f890714850d56c9a833c3e38570544f690003483
