### ISSUE TITLE
publication d'un article de pas à pas : uniquement dans l'ordre des brouillons ?

### ISSUE THREAD

**Issue by dbrizard** [lairdubois/lairdubois#59]
J'ai plusieurs pas à pas sur le feu que j'alimente petit à petit.
Dans ces pas à pas, j'ai plusieurs articles sous forme de brouillon.
Imaginons:
- article 1 (publié)
- article 2 (brouillon 1)
- article 3  (brouillon 2)

Or j'ai l'impression qu'il n'est pas possible de publier brouillon 2 avant brouillon 1.
Cela fait deux fois, au moins, que je clique sur publier sur l'article 3 (brouillon2) et qu'on lieu de le publier, il publie l'article 2 (brouillon 1) à la place.

J'espère que le problème est clair.
Je ne sais pas si c'est un comportement voulu ou prévu ou imprévu...

**Comment by bbeaulant** [comment]
Hmm, t'es sur que c'est pas plutôt l'ordre des articles qui change ?

**Comment by bbeaulant** [comment]
Je viens de corriger un peu le fonctionnement du tri des articles de pas à pas et ça aura certainement moins d'effet de bord :)
Tu me diras si tu y vois des problèmes.

**Comment by dbrizard** [comment]
Non, il me semble que l'ordre ne change pas.
___
Ok, je verrais si j'ai toujours le problème, merci.

@dneis
 :wink:
