### ISSUE TITLE
Nom scientifique

### ISSUE THREAD

**Issue by hedjour** [lairdubois/lairdubois#6]
Bonjour
Autre idée je n'ai pas eu le temps de me plonger dans le code pour proposer une pull request mais il pourrait être agréable d'automatisé l'affichage en italique des noms scientifiques. Respectant ainsi la règle pour les noms latins.
Merci

**Comment by bbeaulant** [comment]
Tu veux dire juste changer le style ?

**Comment by hedjour** [comment]
Oui un nom scientifique s'écrit toujours en italique.
Du coup quand on regarde la fiche il peut être bon qu'il s'affiche en italique.

**Comment by bbeaulant** [comment]
Ca me semble facile à résoudre alors ;)

**Comment by bbeaulant** [comment]
Corrigé par le dernier commit : https://github.com/lairdubois/lairdubois/commit/f442a816ebd2c6d5fc43f14d4e3e0754e7ce7759
