### ISSUE TITLE
Plantage editeur markdown sur Android

### ISSUE THREAD

**Issue by b1nj** [lairdubois/lairdubois#62]
Pour continuer la discussion commencé ici : https://www.lairdubois.fr/questions/3958-lenteurs-dingues-lors-de-la-redaction-sur-android.html
L'éditeur markdown plante sous Android.

L'éditeur est ici : http://www.taufanaditya.com/bootstrap-markdown/
Il n'y a pas eu de nouvelle mise à jour sauf à passer sur une autre version de boostrap.

La librairie se trouve ici : https://github.com/lairdubois/lairdubois/blob/master/src/Ladb/CoreBundle/Resources/assets/js/bootstrap-markdown/bootstrap-markdown-v1.js

Je continue de regarder le problème.

**Comment by bbeaulant** [comment]
Wep, j'avais pas pu passé à la nouvelle version et pas l'énergie d'écrire mon propre éditeur :).
Et en plus le bootstrap-markdown de LADB est une version modifiée pour pouvoir y ajouter les boutons que je voulais.

**Comment by bbeaulant** [comment]
Après, je suis pas bloqué à utiliser cette lib. Faut juste soit le réécrire, soit trouver une lib qui ait les mêmes fonctions de préécrire le markdown.

**Comment by b1nj** [comment]
Il faudrait d'abord isoler le problème. Cela peut être autre chose, notamment les scripts autosize
jquery-textcomplete que tu site.

**Comment by b1nj** [comment]
Voici le résultat de mes premiers test :

- J'ai désactivé markdown et laissé ladbTextcompletify :  c'est ok
- J'ai installé sur une page de test uniquement l'éditeur markown seul avec la même version que ldb : c'est ok.

**Comment by bbeaulant** [comment]
Arg, ça va pas nous aider à isoler si les deux marchent l'un sans l'autre...

**Comment by bbeaulant** [comment]
Un indice qui peut-être en est pas un. Mais j'ai le sentiment d'avoir commencé à entendre parlé de ralentissements quand j'ai mis en place le LazyLoad sur les images. Un autre JS qui écoute le scroll.

Comment fais-tu tes tests ?

**Comment by b1nj** [comment]
En effet je confirme qu'en enlevant le lazyload, c'est ok.
L’événement "scroll" ralentie la page et le "touchmove" la fait presque planter.
Pas de problème avec les autres événements.

C'est ici : 

https://github.com/lairdubois/lairdubois/blob/32ae00498a239d84bed2bff955f26d863da211cc/app/Resources/views/base.html.twig#L276

J'ai installé lazy sur ma page de test avec l'éditeur Markdown, mais je n'arrive pas à reproduire le bug : http://www.b1nj.fr/airdubois/

Je continue demain.

Pour tester j'ai juste copié le code source de la page.
Je tenterai d'installer le site quand j'aurai un peu plus de temps.

**Comment by bbeaulant** [comment]
Merci pour ces tests !
Dans mon souvenir, j'avais ajouté toutes ces écoutes sur les evt, parce que sinon sur mobile, ça ne chargeait pas les lazy dans les divers cas.
La question va être de savoir comment apporter une solution. 
- Une autre lib de lazyload qui repose sur des evt plus "modernes" ([yall.js](https://github.com/malchata/yall.js)) ?
- Ne pas écouter les evt sur mobile et donc pas de lazyload ? (c'est dommage, parce que ça décharge bien le serveur)
- ...

**Comment by Plonk42** [comment]
Hello, pour référence et si ça aide, j'ai constaté de très fort ralentissement dans la rédaction d'un commentaire, sur un laptop récent tournant Ubuntu 20.04 et Firefox 77.0.1.

Je n'ai pas du tout investigué encore (je me suis inscrit aujourd'hui :) ), mais je suis tombé par hasard sur cette issue donc je le note ici si ça peut aider. Je peux jeter un coup d'oeil plus avancé mais je n'ai jamais fait de dev web de ma vie.

**Comment by Plonk42** [comment]
Une analyse un peu plus poussée. J'ai l'impression que la saisie ne rame pas tout de suite, mais comment à ramer soit avec le temps, soit avec la longueur du commentaire (j'ai testé avec un commentaire sur cette page : https://www.lairdubois.fr/ateliers/328-construction-atelier-ossature-bois.html).

L'analyseur de performance de Firefox est clair : dès que j'écris dans la zone de commentaire, le frame rate s'effondre (60fps tant que je ne fais rien, 3fps quand je tape au clavier). C'est la zone rouge dans la capture attachée. En se focalisant uniquement sur cette période, on voit qu'on passe quasiment tout notre temps dans la manipulation du DOM, appelé par la fonction `z` du script `27c36d2.js`  à la ligne 1636 (merci l'obfuscation).

![Screenshot from 2020-06-17 21-38-41](https://user-images.githubusercontent.com/3908084/84943399-94944b00-b0e4-11ea-9529-cf01095cf64b.png)

`27c36d2.js` est en fait jQuery UI, et la ligne 1636 appartient à `Zepto Lazy`. Ça confirmerait donc que même sur PC (Ubuntu + FF), `lazy()` soit le coupable.

![Screenshot from 2020-06-17 21-47-23](https://user-images.githubusercontent.com/3908084/84943415-9958ff00-b0e4-11ea-81d4-574f61bc816f.png)

**Comment by bbeaulant** [comment]
Arg, merci pour les investigation @Plonk42. Il va falloir trouver à remplacer cette lib ou la désactiver à l'édition dun champ de texte alors ...

**Comment by b1nj** [comment]
Je penses avoir compris. Le problème se trouve bien ici :

https://github.com/lairdubois/lairdubois/blob/32ae00498a239d84bed2bff955f26d863da211cc/app/Resources/views/base.html.twig#L276

Avec ce code, tu créé une nouvelle instance de Lazy à chaque événements. Il faut mieux utiliser la metode update() de Lazy.

Aussi, quand on utilise un événement de type scroll, il faut mettre un timmer pour éviter les problèmes d'appel trop fréquent. La librairie lazy, le fait par exemple ici : 

https://github.com/eisbehr-/jquery.lazy/blob/dfd9bbd33bb040d5592f9989f7ee4656aa238184/jquery.lazy.js#L607

Si tu as vraiment besoin des événements supplémentaires (load orientationchange touchmove focus) que la librairie ne propose pas de base, tu peux peut être les rajouter directement dans le fichier lazy ici ?

https://github.com/eisbehr-/jquery.lazy/blob/dfd9bbd33bb040d5592f9989f7ee4656aa238184/jquery.lazy.js#L255

Ou sinon ce genre de truc :

```javascript
var scrollTimer = null;

$lazy = $('[data-src]').Lazy({
    effect: "show",
    effectTime: 0,
    threshold: 0,
    chainable: false
});

function lazyLoad() {
    if (scrollTimer) {
        clearTimeout(scrollTimer);   // clear any previous pending timer
    }
    scrollTimer = setTimeout(function() { 
        $lazy.update();
    }, 100);   // set new timer
}

$(window).on('load orientationchange  touchmove focus', lazyLoad); 
```

**Comment by bbeaulant** [comment]
Salut @b1nj, j'ai fais une petite mise à jour en tenant compte de tes retours.

> Si tu as vraiment besoin des événements supplémentaires (load orientationchange touchmove focus) que la librairie ne propose pas de base, tu peux peut être les rajouter directement dans le fichier lazy ici ?

Tu veux dire que la lib de base bind déjà le scroll ?

**Comment by b1nj** [comment]
Super !

Oui, scroll et resize.

**Comment by bbeaulant** [comment]
Ok, ben je sais plus dire pourquoi j'avais ajouté le bind de l'evt scroll alors ...

**Comment by b1nj** [comment]
Et pour les autres événements (load orientationchange  touchmove focus) tu avais eu des problèmes, c'est bien cela ?
