### ISSUE TITLE
Page question

### ISSUE THREAD

**Issue by hedjour** [lairdubois/lairdubois#7]
Une proposition avoir une page échange/ question un peu à la stackoverflow en conservant ton système approbation des réponses et les réponses fortement désapprouvées serait supprimée ?
A réfléchir pour avoir quelques chose qui ne te grossissent pas trop le site.
Et peut être noter les questions utile ou non mais celà permettrais surtout de pouvoir les organiser.

**Comment by bbeaulant** [comment]
Je vote pour. Et j'avais déjà lancé une discussion sur le sujet ici : https://www.lairdubois.fr/blog/53-reflexions-sur-une-nouvelle-section-de-discussion-questions.html

Pour le petite histoire, c'est une fonctionnalité que j'ai mis au tout début de le vie du site. Et elle n'a pas été comprise. Ca ne fonctionne pas comme un forum et c'est une chose qu'il faut apprendre. Et j'avais mis de côté le truc par envie de me concentrer sur le reste.

**Comment by hedjour** [comment]
Du coup maintenant c'est fait et merci beaucoup :) on en apprends tous les jours dans cette partie :)
Je te propose de clore ce problème.

**Comment by bbeaulant** [comment]
Ca marche, merci !
