### ISSUE TITLE
Erreur 500 sur la suppression d'un processus

### ISSUE THREAD

**Issue by lobodol** [lairdubois/lairdubois#70]
Bonjour,

J'ai souhaité supprimer un processus de test que j'avais créé et je tombe sur une erreur 500.
Voici l'URL en question : [GET] _processus 1071_

Je n'ai pas réussi à reproduire l'anomalie en local.

Faites-moi savoir si vous avez besoin de plus d'info.

**Comment by bbeaulant** [comment]
Salut,

C'est en effet un bug. Merci de l'avoir signalé.
Problème corrigé https://github.com/lairdubois/lairdubois/commit/4870a6cc65fb9847965b7eefd079541fe1fe7a4d

(PS : J'ai retiré le lien du commentaire, ce dernier n'ayant pas vocation à être indexé par les moteurs de recherche.)
