### ISSUE TITLE
Je ne parviens pas à déposer un plan pdf

### ISSUE THREAD

**Issue by etienne-monier** [lairdubois/lairdubois#76]
Bonjour,

J'ai récemment essayé de déposer un plan sur ldb.

J'ai réussis à déposer toutes les informations et fichiers, sauf le fichier de plan. L'ayant réalisé sur logiciel de CAO, il est en format pdf (il a été transmis à Boris).

Problème : lors du téléchargement du fichier, l'opération s'intéromp et une notification rouge apparaît en haut de l'écran avec l'indication "error".

![tmp_issue](https://user-images.githubusercontent.com/32652388/111636518-dc254000-87f8-11eb-8093-f5f120de3c1a.png)

J'ai essayé avec d'autres pdf générés à partir d'autres logiciels, mais rien n'y fait. Alors en attendant, j'y ai laissé un classeur excel vide.

Merci pour votre aide :)

**Comment by bbeaulant** [comment]
Salut Etienne,

Merci. Il semble que ça vienne d'une restriction de sécurité dans la configuration de l'analyser de PDF. Je vais voir ce que je peux faire.

**Comment by bbeaulant** [comment]
Salut Etienne,

Le problème est désormais résolu.

**Comment by etienne-monier** [comment]
Super ! Merci Boris :)
On te l'a souvent dit, mais merci encore pour ce chouette site :)
