### ISSUE TITLE
Pargage de processus privé avec d'autre utilisateurs de l'air du bois

### ISSUE THREAD

**Issue by XavierBerger** [lairdubois/lairdubois#80]
### Contexte
Je m'apprête à construire un établi en collaboration avec un professionnel rencontré sur l'air du bois.  
Dans le cadre de cette collaboration, je suis en train de créer un processus qui décrira les étapes de notre collaboration.  
La création de ce processus va donc nécessiter quelques échanges avant d'être validé.  
De même, lors de son exécution, il va pouvoir évoluer.  

### Besoins principal
* J'aimerai pouvoir partager ce processus avec un autre membre de l'Air du Bois pour collaborer sur ce processus sans le rendre public avant sa finalisation.

### Besoins complémentaires
* Dans le cadre d'une collaboration, il pourrait être intéressant d'autoriser l'édition d'un processus par une tierce personne
* Il pourrait aussi être intéressant d'avoir un historique de modification et pouvoir revenir en arrière .

**Comment by bbeaulant** [comment]
Bonjour Xavier,

Le seul moyen à l'heure actuelle de partager un processus à plusieurs est de créer un collectif et de créer le processus "en tant que" ce collectif. Ainsi tous les membres du collectif pourront avoir accès au processus même s'il n'est pas publié.

> Il pourrait aussi être intéressant d'avoir un historique de modification et pouvoir revenir en arrière .

Ca y a pas. Et clairement c'est pas un petit truc à faire. Pour ma part, je n'ai plus le temps (les moyens et l'envie) de reprendre ce module de processus :)

**Comment by XavierBerger** [comment]
Merci Boris pour ces réponses. Finalement j'ai publié mon processus (incomplet) en prévenant dans la description qu'il est en cours d'élaboration.
Je comprends que ces nouvelles fonctionnalités sont complexe à mettre en oeuvre pour une partie du site somme toute pas très usitée. Je clos donc cette issue de partage d'idée.

Merci pour ton travail sur l'air du bois.

**Comment by bbeaulant** [comment]
@XavierBerger, avec un collectif, ça aurait pu fonctionné et c'est même d'ailleurs pour ce type d'usage que j'avais créé la fonction de collectif :)
Une prochaine fois.
