### ISSUE TITLE
Création d'un livre - Problème d'affichage d'un nom de champ

### ISSUE THREAD

**Issue by jbfagotfede39** [lairdubois/lairdubois#86]
Bonjour,

Une petite coquille que je souhaitais signaler : lors de la création d'une fiche "livre", le champ affiché en haut à droite en orange au-dessus de `Couverture` est affiché comme `knowledge.book.field.title` et non comme `Titre`, ce qui était initialement prévu, j'imagine.

Je joins une capture d'écran.
Désolé, je ne vais pas jusqu'à proposer une pull request, n'étant pas assez calé...

Merci pour tout le travail réalisé !

![Capture d’écran 2021-04-04 à 15 01 49](https://user-images.githubusercontent.com/15885207/135757276-ed3975d6-fb04-4187-9a6f-49fd2a882834.png)

**Comment by bbeaulant** [comment]
Merci, voilà qui est corrigé :)

**Comment by jbfagotfede39** [comment]
> Merci, voilà qui est corrigé :)

;-)
