### ISSUE TITLE
Impossible d'ajouter des images dans un bloc d'image lors de l'édition

### ISSUE THREAD

**Issue by etienne-monier** [lairdubois/lairdubois#98]
Bonjour,

je viens de terminer un pas-à-pas et j'ai voulu ajouter une image dans un bloc d'images. Je suis allé dans l'article en question, puis dans le bloc d'images.

Le problème, c'est que je ne peux pas ajouter d'image. Il n'y a pas de bouton. Je ne peux pas non plus ajouter un autre bloc en-dessous, il faut un bloc de texte non-vide entre les deux

![bug](https://user-images.githubusercontent.com/32652388/159186681-5c5ef2e6-d405-40fa-a785-71a2544015ee.png)
.

**Comment by bbeaulant** [comment]
Bonjour Etienne,

C'est un fonctionnement normal et voulu.
Les blocs d'image ne peuvent pas contenir plus de 10 images et plusieurs blocs d'images ne peuvent pas ce suivre.

Ceci afin d'inciter le contributeur à mettre du détail textuel :)
